project:
  type: website
  output-dir: docs

website:
  favicon: media/favicon.ico
  title: "Yazeed Aljohani"
  navbar:
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - resources.qmd
     - projects.qmd
     - Rsume.qmd

format:
  html:
    theme: lux
    css: styles.css
