project:
  type: website
  output-dir: docs

website:
  title: "Yazeed Aljoahni"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: resources
format:
  html:
    theme: cosmo
    css: styles.css
