project:
  type: website
  output-dir: docs

website:
  favicon: media/favicon.ico
  title: "Yazeed Aljohani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
format:
  html:
    theme: lux
    css: styles.css
